In [3]:
import tensorflow as tf
from tensorflow import keras

In [4]:
tf.__version__

'2.10.0'

In [2]:
keras.__version__

'2.10.0'

In [5]:
class SimpleDense(keras.layers.Layer):
    def __init__(self, units, activation=None):
        super().__init__()
        self.units = units
        self.activation = activation
        
    def build(self, input_shape):
        input_dim = input_shape[-1]
        self.W = self.add_weight(shape=(input_dim, self.units),
                                initializer="random_normal")
        self.b = self.add_weight(shape=(self.units),
                                initializer="zeros")
        
    def call(self, inputs):
        y = tf.matmul(inputs,self.W) + self.b
        
        if self.activation is not None:
            y = self.activation(y)
            
        return y

In [8]:
my_dense = SimpleDense(units=32, activation=tf.nn.relu)

input_tensor = tf.ones(shape=(2,784))

2023-02-26 09:07:36.410392: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [10]:
print(input_tensor)

tf.Tensor(
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]], shape=(2, 784), dtype=float32)


In [11]:
# W = (784,32)
# b = (32,)

output_tensor = my_dense(input_tensor)

In [14]:
my_dense.W.shape

TensorShape([784, 32])

In [15]:
my_dense.W

<tf.Variable 'simple_dense_1/Variable:0' shape=(784, 32) dtype=float32, numpy=
array([[-0.02740622, -0.06080721, -0.01782965, ..., -0.05192655,
         0.02794713,  0.05461033],
       [-0.08020504,  0.05934129, -0.01324837, ..., -0.01983051,
         0.00844802, -0.05417671],
       [ 0.02810974,  0.04179709, -0.06390937, ...,  0.03005138,
        -0.00991286, -0.00516876],
       ...,
       [ 0.07412083, -0.01628413,  0.00617072, ...,  0.01345807,
         0.1019484 , -0.03426332],
       [ 0.01131263,  0.04441418,  0.02229792, ..., -0.04515712,
         0.00277336, -0.02032232],
       [ 0.03369704, -0.00887015, -0.05466058, ..., -0.00554247,
        -0.00432999,  0.00234378]], dtype=float32)>

In [17]:
my_dense.b.shape

TensorShape([32])

In [18]:
print(output_tensor)

tf.Tensor(
[[0.4972052  0.         0.26203343 0.46193242 0.7118495  1.7098267
  2.03727    0.5900648  0.         1.6438937  1.5810475  0.
  1.0627902  0.         0.         0.1990368  0.         0.03802975
  0.1726898  0.         0.         0.         0.15256983 0.
  0.         0.         1.306758   0.35992098 0.49521613 0.
  0.         0.8471941 ]
 [0.4972052  0.         0.26203343 0.46193242 0.7118495  1.7098267
  2.03727    0.5900648  0.         1.6438937  1.5810475  0.
  1.0627902  0.         0.         0.1990368  0.         0.03802975
  0.1726898  0.         0.         0.         0.15256983 0.
  0.         0.         1.306758   0.35992098 0.49521613 0.
  0.         0.8471941 ]], shape=(2, 32), dtype=float32)


In [21]:
from tensorflow.keras import layers, models